dash/urls.py
from . import views
from django.conf.urls import url
app_name = 'dash'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^user_profile$', views.user_profile, name='user_profile'),
    url(r'^pic$', views.upload_pic, name='pic'),
    url(r'^logout_user$', views.logout_user, name='logout_user')
]

prijatie/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('register.urls', namespace='register')),
    url(r'^dash/', include('dash.urls', namespace='dash')),
]

register/urls.py
from django.conf.urls import url
from . import views
app_name = 'register'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^index2', views.index2, name='index2'),
    url(r'^index3', views.index3, name='index3'),
    url(r'^register',views.client_register, name='client_register'),
    url(r'^login', views.client_login, name = 'client_login'),
    url(r'^org_login', views.org_login, name='org_login'),
    url(r'^org_register', views.org_register, name='org_register')
]

dash/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    userim = models.ForeignKey(User, null=True)
    avatar = models.TextField(null=True)

register/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

dash/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from .models import UserProfile
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

def index(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('register:index'))
    else:
        try :
            userprofile = UserProfile.objects.get(userim=request.user)
        except :
            userprofile = request.user
        context = {
            'userprofile' : userprofile
        # 'username' : userprofile.userim.username,
        # 'image' : userprofile.avatar
        }
        template = 'dash/index.html'
        return render(request, template, context)

def user_profile(request):
    template = 'dash/user_profile.html'
    return render(request, template)

def upload_pic(request):
    pic = request.POST['pic']
    p = UserProfile(userim=request.user, avatar=pic)
    p.save()
    return redirect('dash:index')

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('register:index'))

register/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.admin import User
from django.contrib.auth import authenticate, login
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse

def index(request):
    if not request.user.is_authenticated():
        template = 'register/index.html'
        return render(request, template)
    else:
        return HttpResponseRedirect(reverse('dash:index'))

def contact(request):
    if not request.user.is_authenticated():
        template = 'register/contact.html'
        return render(request, template)
    else:
        return HttpResponseRedirect(reverse('dash:index'))

def index2(request):
    if not request.user.is_authenticated():
        template = 'register/index2.html'
        return render(request, template)
    else:
        return HttpResponseRedirect(reverse('dash:index'))

def index3(request):
    if not request.user.is_authenticated():
        template = 'register/index3.html'
        return render(request, template)
    else:
        return HttpResponseRedirect(reverse('dash:index'))

def client_register(request):
    if not request.user.is_authenticated():
        user = request.POST['usernamesignup']
        mail = request.POST['emailsignup']
        password = request.POST['passwordsignup']
        users = User.objects.create_user(username=user,email=mail, password=password)
        users.save()
        login(request,user)
        return HttpResponseRedirect(reverse('dash:index'))
    else:
        return HttpResponseRedirect(reverse('dash:index'))

def client_login(request):
    user = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=user, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('dash:index'))
    else:
        return HttpResponse("Invalid credentials")

def org_register(request):
    if not request.user.is_authenticated():
        username = request.POST['user_name']
        mail = request.POST['mail']
        password = request.POST['password']
        user = User.objects.create_user(username=username, email=mail, password=password)
        login(request, user)
        return HttpResponseRedirect(reverse('dash:index'))
    else:
        return HttpResponseRedirect(reverse('dash:index'))

def org_login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('dash:index'))
    else:
        return HttpResponse("Invalid credentials")

dash/templates/dash/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Bootstrap Admin Theme</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="{% static 'dash/vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet" type="text/css">

    <link href="{% static 'dash/vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

    <link href="{% static 'dash/dist/css/sb-admin-2.css' %}" rel="stylesheet">

    <link href="{% static 'dash/vendor/morrisjs/morris.css' %} " rel="stylesheet">

    <link href="{% static 'dash/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'dash:index' %}">Dash</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        </li>
                    </ul>
                </li>

                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="{% url 'dash:user_profile' %}"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                </li>
                    <a class="dropdown-toggle" style="padding:30px" href="logout_user">Log out</a>
            </ul>
            {% block side %}
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        </li>
                        <li>
                            <a href=""><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>

                        <li>
                            <a href="tables.html"><i class="fa fa-table fa-fw"></i> Tables</a>
                        </li>
                        <li>
                            <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Forms</a>
                        </li>

                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            {% endblock %}
            <!-- /.navbar-static-side -->
        </nav>
    </div>
    {% block body %}
    {% endblock %}
    <script src="{% static 'dash/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'dash/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'dash/vendor/metisMenu/metisMenu.min.js' %}"></script>
    <script src="{% static 'dash/vendor/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'dash/vendor/morrisjs/morris.min.js' %}"></script>
    <script src="{% static 'dash/data/morris-data.js' %}"></script>
    <script src="{% static 'dash/dist/js/sb-admin-2.js' %}"></script>

</body>

</html>

register/templates/register/index.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Home</title>
<link rel="icon" type="image/x-icon" href="\Screenshot_45_.ico" />
<meta charset="utf-8">
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'register/css/reset.css' %}" type="text/css" media="all"/>
<link rel="stylesheet" href="{% static 'register/css/layout.css' %}" type="text/css" media="all"/>
<link rel="stylesheet" href="{% static 'register/css/style.css' %}" type="text/css" media="all"/>
<script type="text/javascript" src="{% static 'register/js/jquery-1.6.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/cufon-yui.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/cufon-replace.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/Vegur_700.font.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/Vegur_400.font.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/Vegur_300.font.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/jquery.easing.1.3.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/tms-0.3.js' %} "></script>
<script type="text/javascript" src="{% static 'register/js/tms_presets.js' %} "></script>
<script type="text/javascript" src="{% static 'register/js/backgroundPosition.js' %} "></script>
<script type="text/javascript" src="{% static 'register/js/atooltip.jquery.js' %} "></script>
<script type="text/javascript" src="{% static 'register/js/script.js' %}"></script>

</head>
<body  bgcolor="#FFFFFF">
<div class="body1">
	<div class="main">
<!-- header -->
		<header>
			<div class="wrapper">
				<h1></a></h1>
				<nav>
					<ul id="top_nav">
						<li><a href="{% url 'register:index' %}"><img src="{% static 'register/images/top_icon1.gif' %}" alt=""></a></li>
						<li><a href="#"><img src="{% static 'register/images/top_icon2.gif' %}" alt=""></a></li>
						<li class="end"><a href="{% url 'register:contact' %}"><img src="{% static 'register/images/top_icon3.gif'%}" alt=""></a></li>
						<li class="end"><a href="{% url 'register:index2' %}" > &nbsp; &nbsp; &nbsp;
					<strong> Login/SignUP </strong></a></li>
					</ul>
				</nav>
				<nav>
					<ul id="menu">
						<li id="menu_active"><a href="{% url 'register:index' %}">Home</a></li>
						<li><a href="#">Progress</a></li>
						<li><a href="{% url 'register:index2' %}">Register</a></li>
					    <li><a href="#">Portal</a></li>
						<li><a href="{% url 'register:contact' %}">Contact</a></li>
					</ul>
				</nav>
			</div>
			<div class="slider">
				<ul class="items">
					<li>
						<img src="http://www.2classnotes.com/wp-content/uploads/2016/04/Children-from-Nardan-Basti-on-Mehrauli-Badarpur-Road-at-a-Matri-Sudha-centre.jpg" alt="">
						<div class="banner">
							<div class="wrapper"><span><em>Help</em></span></div>
							<div class="wrapper"><strong>Those Who<em>Need</em>It”</strong></div>
						</div>
					</li>
					<li>
						<img src="https://s-media-cache-ak0.pinimg.com/originals/15/fd/0c/15fd0c4366e8bca0821e8f81cfe1983c.jpg" alt="">
						<div class="banner">
							<div class="wrapper"><span>“MAKE all the CHILDREN</span></div>
							<div class="wrapper"><strong>Smile”</strong></div>
						</div>
					</li>
					<li>
						<img src="https://performancemarks.files.wordpress.com/2013/09/origin_9140556495.jpg?w=652&h=435" alt="">
						<div class="banner">
							<div class="wrapper"><span>“TOGETHER we can CHANGE</span></div>
							<div class="wrapper"><strong>Many Young LIVES”</strong></div>
						</div>
					</li>
				</ul>
				<ul class="pagination">
					<li id="banner1"><a href="#">CHECK <span>Their Report</span></a></li>
					<li id="banner2"><a href="#">Join<span>Them Here</span></a></li>
					<li id="banner3"><a href="#">Help<span>children</span></a></li>
				</ul>
			</div>
<!-- / header -->
<!-- content -->
		
				
		
			
<!-- / content -->
	<br/><br/>			<br/>	<br/><br/>			<br/>
<!-- footer -->
		<footer>
			<div class="wrapper">
				<a href="index.html" id="footer_logo"><span>Prijatie</span></a>
				<ul id="icons">
					<li><a href="#" class="normaltip" title="Facebook"><img src="images/icon1.gif" alt=""></a></li>
					<li><a href="#" class="normaltip" title="Twitter"><img src="images/icon2.gif" alt=""></a></li>
					<li><a href="#" class="normaltip" title="Linkedin"><img src="images/icon3.gif" alt=""></a></li>
				</ul>
			</div>	
		


			<div class="wrapper">
				<nav>
					<ul id="footer_menu">
						<li class="active"><a href="index.html">Home</a></li>
						<li><a href="Mission.html">Progress</a></li>
						<li><a href="News.html">Register</a></li>
						<li><a href="Help.html">Portal</a></li>
						<li class="end"><a href="Contact.html">Contact</a></li>
					</ul>
				</nav>
				<div class="tel"><span>+91</span>7760562281</div>
			</div>
		
		</footer>
<!-- / footer -->
	</div>
</div>
<script type="text/javascript">Cufon.now();</script>
<script>
$(window).load(function(){
	$('.slider')._TMS({
		preset:'zabor',
		easing:'easeOutQuad',
		duration:800,
		pagination:true,
		banners:true,
		waitBannerAnimation:false,
		slideshow:6000,
		bannerShow:function(banner){
			banner
				.css({right:'-700px'})
				.stop()
				.animate({right:'0'},600, 'easeOutExpo')
		},
		bannerHide:function(banner){
			banner
				.stop()
				.animate({right:'-700'},600,'easeOutExpo')
		}
	})
	$('.pagination li').hover(function(){
		if (!$(this).hasClass('current')) {
			$(this).find('a').stop().animate({backgroundPosition:'0 0'},600,'easeOutExpo', function(){$(this).parent().css({backgroundPosition:'-20px 0'})});
		}
	},function(){
		if (!$(this).hasClass('current')) {
			$(this).css({backgroundPosition:'0 0'}).find('a').stop().animate({backgroundPosition:'-250px 0'},600,'easeOutExpo');
		}
	})
})
</script>
</body>
</html>

register/templates/register/index2.html
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
    <head>
		{% load staticfiles %}
        <meta charset="UTF-8" />
        <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
        <title>USer's Login/SignUp</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <meta name="description" content="Login and Registration Form with HTML5 and CSS3" />
        <meta name="keywords" content="html5, css3, form, switch, animation, :target, pseudo-class" />
        <meta name="author" content="Codrops" />
        <link rel="shortcut icon" href="{% static '../favicon.ico' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'register/css/demo.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'register/css/style2.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'register/css/animate-custom.css' %}" />
		<link rel="icon" type="image/x-icon" href="\Screenshot_45_.ico" />
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'register/css/reset.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="[% static 'register/css/layout.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'register/css/style.css' %}" type="text/css" media="all">
<script type="text/javascript" src="{% static 'register/js/jquery-1.6.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/cufon-yui.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/cufon-replace.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/Vegur_700.font.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/Vegur_400.font.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/Vegur_300.font.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/jquery.easing.1.3.js.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/tms-0.3.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/tms_presets.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/backgroundPosition.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/atooltip.jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'register/js/script.js' %}"></script>
<style type="text/css">


.icon1 {
 text-align: left;
}
.username {
 text-align: left;
}

</style>

    </head>
    <body>
		<header>
			<div class="wrapper">
				<h1></a></h1>
				<nav>
					<ul id="top_nav">
						<li><a href="index.html"><img src="images/top_icon1.gif" alt=""></a></li>
						<li><a href="#"><img src="images/top_icon2.gif" alt=""></a></li>
						<li class="end"><a href="Contact.html"><img src="images/top_icon3.gif" alt="">
						<li class="end"><a href="index3.html" > &nbsp; &nbsp; &nbsp;
					<strong> Login/SignUP </strong></a></li>
					</ul>
				</nav>
				<nav>
					<ul id="menu">
						<li><a href="{% url 'register:index' %}">Home</a></li>
						<li><a href="#">Progress</a></li>
						<li id="menu_active"><a href="{% url 'register:index2' %}">Register</a></li>
					    <li><a href="#">Portal</a></li>
					<li><a href="{% url 'register:contact' %}">Contact</a></li>
					</ul>
				</nav>
			</div>
        <div class="container">
            <!-- Codrops top bar -->
            <div class="codrops-top">
               
               
                <div class="clr"></div>
            </div><!--/ Codrops top bar -->
            <header>
              
				<nav class="codrops-demos">
					<span>Click <strong>"Join us"</strong>here</span>
				
					<a href="index2.html" class="current-demo">Organization</a>
					<a href="index3.html">Client</a>
				</nav>
            </header>
            <section>				
                <div id="container_demo" style="padding-top: 25px;" >
                    <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
                    <a class="hiddenanchor" id="toregister"></a>
                    <a class="hiddenanchor" id="tologin"></a>
                    <div id="wrapper">
                        <div id="login" class="animate form">
                            <form action="org_login" method="post">
                                {% csrf_token %}
                                <h1>Log in</h1> 
                                <p align="left">
								&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;
                                   <br/><br/> <label for="username" class="uname"  for="username" data-icon="u">  Your email or username</label>
                                    <input id="username" name="username" required="required" type="text" placeholder="username.usermail@mail.com"/>
                                </p>
                                <p> &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;
                                    <label for="password" class="youpasswd" data-icon="p"> Your password </label>
                                    <input id="password" name="password" required="required" type="password" placeholder="eg. X8df!90EO" /> 
                                </p>
                                <p class="keeplogin"> 
									<input type="checkbox" name="loginkeeping" id="loginkeeping" value="loginkeeping" /> 
									<label for="loginkeeping">Keep me logged in</label>
								</p>
                                <p class="login button"> 
                                    <input type="submit" value="Login" /> 
								</p>
                                <p class="change_link">
									Not a member yet ?
									<a href="#toregister" class="to_register">Join us</a>
								</p>
                            </form>
                        </div>

                        <div id="register" class="animate form" style="padding-top: 20px;">
                            <form  action="org_register" method="post">
                                {% csrf_token %}
                                <h1> Sign up </h1> 
                                <p> &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;&nbsp; &nbsp;  
                                    <label for="usernamesignup" class="uname" >
									 Firsusername</label>
                                    <input id="usernamesignup" name="user_name" required="required" type="text" placeholder="Username" data-icon="u"/>
                                </p>
                                <p> 
                                    <label for="emailsignup" class="youmail" data-icon="e" > Your email</label>
                                    <input id="emailsignup" name="mail" required="required" type="email" placeholder="mysupermail@mail.com"/>
                                </p>
                                <p> 
                                    <label for="passwordsignup" class="youpasswd" data-icon="p">Your password </label>
                                    <input id="passwordsignup" name="password" required="required" type="password" placeholder="eg. X8df!90EO"/>
                                </p>
                                <p> 
                                    <label for="passwordsignup_confirm" class="youpasswd" data-icon="p">Please confirm your password </label>
                                    <input id="passwordsignup_confirm" name="passwordsignup_confirm" required="required" type="password" placeholder="eg. X8df!90EO"/>
                                </p>
                                <p class="signin button"> 
									<input type="submit" value="Sign up"/> 
								</p>
                                <p class="change_link">  
									Already a member ?
									<a href="#tologin" class="to_register"> Go and log in </a>
								</p>
                            </form>
                        </div>
						
                    </div>
                </div>  
            </section>
        </div>
		</header>
		<footer style="padding: 64px 32px;">
			<div class="wrapper">
				<a href="index.html" id="footer_logo"><span>Prijatie</span></a>
				<ul id="icons">
					<li><a href="#" class="normaltip" title="Facebook"><img src="images/icon1.gif" alt=""></a></li>
					<li><a href="#" class="normaltip" title="Twitter"><img src="images/icon2.gif" alt=""></a></li>
					<li><a href="#" class="normaltip" title="Linkedin"><img src="images/icon3.gif" alt=""></a></li>
				</ul>
			</div>	
		


			<div class="wrapper">
				<nav>
					<ul id="footer_menu">
						<li class="active"><a href="index.html">Home</a></li>
						<li><a href="#">Progress</a></li>
						<li><a href="News.html">Register</a></li>
						<li><a href="#">Portal</a></li>
						<li class="end"><a href="Contact.html">Contact</a></li>
					</ul>
				</nav>
				<div class="tel"><span>+91</span>7760562281</div>
			</div>
		
		</footer>
    </body>
</html>